pipeline {
    agent any
    stages {
        stage('Setup parameters') {
            steps {
                script {
                    properties([
                        parameters([
                            string( defaultValue: '/tmp/the-log.log', name: 'LOGFILE', trim: true ),
                        ])
                    ])
                }
            }
        }
        stage('Execute chklog.') {
            steps {
                script {
                    env.DEFAULT_LOCAL_TMP = env.WORKSPACE_TMP
                    env.HOME = env.WORKSPACE

                    sh """
                    echo "Log file is ${LOGFILE}."
                    ls -la ${LOGFILE} .
                    grep FAIL ${LOGFILE}
                    """
                }
            }
        }
    }
}