pipeline {
    agent {
        docker {
            // image 'ansible/ansible:default'
            // image 'willhallonline/ansible'
            image 'gableroux/ansible'
            args '-i --entrypoint='
        }
    }
    stages {
        stage('Setup parameters') {
            steps {
                // PATTERN|INVENTORY|LIMIT|MODULE|DASH_A|EXTRA_PARAMS

                script {
                    properties([
                        parameters([
                            string( defaultValue: 'hosts', name: 'INVENTORY', trim: true ),
                            string( defaultValue: '\'*\'', name: 'LIMIT', trim: true ),
                            string( defaultValue: 'shell', name: 'PLAYBOOK', trim: true ),
                            string( defaultValue: '--list-hosts', name: 'EXTRA_PARAMS', trim: true )
                        ])
                    ])
                }
            }
        }
        stage('Execute AD Hoc Ansible.') {
            steps {
                script {
                    env.DEFAULT_LOCAL_TMP = env.WORKSPACE_TMP
                    env.HOME = env.WORKSPACE

                    sh """
                    echo ${WORKSPACE_TMP}
                    echo ${DEFAULT_LOCAL_TMP}
                    echo "tempuser:x:$(id -u):$(id -g):,,,:${HOME}:/bin/bash" >> /etc/passwd
                    echo "tempuser:x:$(id -G | cut -d' ' -f 2)" >> /etc/group
                    ansible-playbook -i ${INVENTORY} -l "${LIMIT}" ${PLAYBOOK} ${EXTRA_PARAMS} |tee /tmp/the-log.log
                    cat /tmp/the-log.log
                    ls -l /tmp/the-log.log
                    """
                }
            }
        }
    }
}