pipeline {
    agent {
        docker {
            // image 'ansible/ansible:default'
            // image 'willhallonline/ansible'
            image 'gableroux/ansible'
            // args '-i --entrypoint='
            args '-v /var/jenkins_home/logs:/tmp/logs -i --entrypoint='
        }
    }
    stages {
        stage('Setup parameters') {
            steps {
                // PATTERN|INVENTORY|LIMIT|MODULE|DASH_A|EXTRA_PARAMS

                script {
                    properties([
                        parameters([
                            string( defaultValue: 'hosts', name: 'INVENTORY', trim: true ),
                            string( defaultValue: '\'*\'', name: 'LIMIT', trim: true ),
                            string( defaultValue: 'shell', name: 'PLAYBOOK', trim: true ),
                            string( defaultValue: '--list-hosts', name: 'EXTRA_PARAMS', trim: true )
                        ])
                    ])
                }
            }
        }
        stage('Execute Ansible Playbook.') {
            steps {
                script {
                    sh '''
                    # This is only needed for Jenkin running in docker container.
                    # echo "tempuser:x:$(id -u):$(id -g):,,,:${HOME}:/bin/bash" >> /etc/passwd
                    # echo "tempuser:x:$(id -G | cut -d' ' -f 2)" >> /etc/group
                    '''
                    // these two lines where needed for Jenkins running in docker container.
                    env.DEFAULT_LOCAL_TMP = env.WORKSPACE_TMP
                    env.HOME = env.WORKSPACE
                    sh """
                    ansible-playbook -i ${INVENTORY} -l "${LIMIT}" ${PLAYBOOK} ${EXTRA_PARAMS} |tee /tmp/logs/the-log.log
                    cat /tmp/logs/the-log.log
                    ls -l /tmp/logs/the-log.log
                    """
                }
            }
        }
    }
}