pipeline {
    agent {
        docker {
            // image 'ansible/ansible:default'
            // image 'willhallonline/ansible'
            image 'gableroux/ansible'
            args '-i --entrypoint='
        }
    }
    stages {
        stage('Setup parameters') {
            steps {
                // PATTERN|INVENTORY|LIMIT|MODULE|DASH_A|EXTRA_PARAMS

                script {
                    properties([
                        parameters([
                            string( defaultValue: 'all', name: 'PATTERN', trim: true ),
                            string( defaultValue: 'hosts', name: 'INVENTORY', trim: true ),
                            string( defaultValue: '*', name: 'LIMIT', trim: true ),
                            string( defaultValue: 'shell', name: 'MODULE', trim: true ),
                            string( defaultValue: 'pwd' ,name: 'DASH_A', trim: true ),
                            string( defaultValue: '--list-hosts', name: 'EXTRA_PARAMS', trim: true )
                        ])
                    ])
                }
            }
        }
        stage('Execute AD Hoc Ansible.') {
            steps {
                script {
                    sh """
                    env
                    pwd
                    ls -la
                    id
                    # date > $HOME/today.txt
                    # cat $HOME/today.txt
                    export DEFAULT_LOCAL_TMP=${WORKSPACE_TMP}
                    echo $DEFAULT_LOCAL_TMP
                    ansible
                    # ansible ${PATTERN} -i ${INVENTORY} -l ${LIMIT} -m ${MODULE} -a ${DASH_A} ${EXTRA_PARAMS}
                    """
                }
            }
        }
    }
}