pipeline {
    agent any
    stages {
        stage('Setup parameters') {
            steps {
                // PATTERN|INVENTORY|LIMIT|MODULE|DASH_A|EXTRA_PARAMS

                script {
                    properties([
                        parameters([
                            string( defaultValue: 'all', name: 'PATTERN', trim: true ),
                            string( defaultValue: 'hosts', name: 'INVENTORY', trim: true ),
                            string( defaultValue: '*', name: 'LIMIT', trim: true ),
                            string( defaultValue: 'shell', name: 'MODULE', trim: true ),
                            string( defaultValue: 'pwd' ,name: 'DASH_A', trim: true ),
                            string( defaultValue: '--list-hosts', name: 'EXTRA_PARAMS', trim: true )
                        ])
                    ])
                }
            }
        }
        stage('All done') {
            steps {
                script {
                    println("Robinson sucks turds out of dicks!")
                }
            }
        }
    }
}