pipeline {
    agent {
        docker {
            // image 'ansible/ansible:default'
            image 'willhallonline/ansible'
            // image 'gableroux/ansible'
            // args '-i --entrypoint='
            // use -v so that our ansible container will write to
            // the filesystem of jenkins server.
            args '-v /var/jenkins_home/logs:/tmp/logs -i --entrypoint='
        }
    }
    stages {
        stage('Setup parameters') {
            steps {
                // PATTERN|INVENTORY|LIMIT|MODULE|DASH_A|EXTRA_PARAMS

                script {
                    properties([
                        parameters([
                            string( name: 'CMD', trim: true ),
                        ])
                    ])
                }
            }
        }
        stage('Execute AD Hoc Ansible.') {
            steps {
                script {
                    env.DEFAULT_LOCAL_TMP = env.WORKSPACE_TMP
                    env.HOME = env.WORKSPACE

                    sh "ansible ${CMD}"
                }
            }
        }
    }
}