import groovy.json.JsonSlurper
// see https://stackoverflow.com/questions/37864542/jenkins-pipeline-notserializableexception-groovy-json-internal-lazymap
def mopData
def wholeFileData

pipeline {
    agent any
    stages {
        stage('Setup parameters') {
            steps {
                script {
                    properties([
                        parameters([
                            string( defaultValue: './mops/the-mop.json', name: 'MOP_FILE', trim: true ),
                        ])
                    ])
                }
            }
        }
        stage('Pre-Flight (automate MOP review') {
            steps {
                script {
                    wholeFileData = readFile(file: MOP_FILE)
                    println(wholeFileData)
                    mopData = new JsonSlurper().parseText(wholeFileData)
                    println(mopData)
                    // String value1 = response.data.value1

                    mop = mopData.mop
                    print(mop)
                    mop.each {
                        println("comment = [$it.comment]")
                        println("env_vars = [$it.env_var]")
                        println("command = [$it.command]")
                        println("arguments = [$it.arguments]")
                    }
                    mopData = null
                    mop = null
                }
            }
        }
    }
}