def wholeFileData
def ys = new YamlSlurper()

pipeline {
    agent any
    stages {
        stage('Setup parameters') {
            steps {
                // PATTERN|INVENTORY|LIMIT|MODULE|DASH_A|EXTRA_PARAMS

                script {
                    properties([
                        parameters([
                            string( defaultValue: 'the-mop.yaml', name: 'MOP_FILE', trim: true ),
                        ])
                    ])
                }
            }
        }
        stage('Pre-Flight (automate MOP review') {
            steps {
                script {
                    wholeFileData = readFile(file: MOP_FILE)
                    mopData = ys.parseText(wholeFileData)

/********************
---
mop:
   - comment: "Set env var MMRS"
     env_var:
       name: "MMRS"
       value: 'centos*'
     ansible:
       pattern: "all"
       inventory: "hosts"
       limit: "$MMRS"
       module: "shell"
       args: "ls -l /etc | grep group"
**************************/
                    }
                }
            }
        }
        stage('Approve MOP Step-by-Step') {
            steps {
                script {
                    input "Now what?"
                }
            }
        }
        stage('Execute MOP Step-by-Step') {
            steps {
                script {
                    wholeFileData.split('\n').each { String line ->
                        if(line.startsWith('#')) {
                            println("Ignoreing comment:${line}")
                        } else if (line.startsWith("ansible "))  {
                            runAnsibleAction(line)
                        } else if (line.startsWith("ANSIBLEPLAYBOOK|"))  {
                            runAnsiblePlaybookAction(line)
                        } else if (line.startsWith("CHKLOG|"))  {
                            checkLog()
                        } else {
                            println("ERROR Unhandle verb >:${line}")
                            currentBuild.result = 'ABORTED'
                            error('Pre-fligth FAILED! Aborting! Look above for error message.')
                        }
                    }
                }
            }
        }
    }
}

def checkAnsibleAction(String line) {
    println("checkAnsibleAction called with  line = ${line}")
    // def (ACTION, PATTERN, INVENTORY, LIMIT, MODULE, DASH_A, EXTRA_PARAMS) = line.tokenize('|')
    // println("${ACTION}, ${PATTERN}, ${INVENTORY}, [${EXTRA_PARAMS}]")
    build job: 'run_ansible', propagate: true, wait: true, parameters: [
        [$class: 'StringParameterValue', name: 'CMD', value: line + ' --list-hosts']]
}

def checkAnsiblePlaybookAction(String line) {
    println("checkAnsiblePlaybookAction called with  line = ${line}")
    def (ACTION, INVENTORY, LIMIT, PLAYBOOK, EXTRA_PARAMS) = line.tokenize('|')
    build job: 'run_ansibleplaybook', propagate: true, wait: true, parameters: [
        [$class: 'StringParameterValue', name: 'INVENTORY', value: INVENTORY],
        [$class: 'StringParameterValue', name: 'LIMIT', value: LIMIT],
        [$class: 'StringParameterValue', name: 'PLAYBOOK', value: PLAYBOOK],
        [$class: 'StringParameterValue', name: 'EXTRA_PARAMS', value: EXTRA_PARAMS + ' --list-hosts']]
}

def runAnsibleAction(String line) {
    println("runAnsibleAction called with  line = ${line}")
    def (ACTION, PATTERN, INVENTORY, LIMIT, MODULE, DASH_A, EXTRA_PARAMS) = line.tokenize('|')
    println("${ACTION}, ${PATTERN}, ${INVENTORY}, ${LIMIT}, ${MODULE}, [${DASH_A}], ${EXTRA_PARAMS}")
    build job: 'run_ansible', propagate: true, wait: true, parameters: [
        [$class: 'StringParameterValue', name: 'PATTERN', value: PATTERN],
        [$class: 'StringParameterValue', name: 'INVENTORY', value: INVENTORY],
        [$class: 'StringParameterValue', name: 'LIMIT', value: LIMIT],
        [$class: 'StringParameterValue', name: 'MODULE', value: MODULE],
        [$class: 'StringParameterValue', name: 'DASH_A', value: DASH_A],
        [$class: 'StringParameterValue', name: 'EXTRA_PARAMS', value: EXTRA_PARAMS]]
}

def runAnsiblePlaybookAction(String line) {
    println("runAnsiblePlaybookAction called with  line = ${line}")
    def (ACTION, INVENTORY, LIMIT, PLAYBOOK, EXTRA_PARAMS) = line.tokenize('|')
    build job: 'run_ansibleplaybook', propagate: true, wait: true, parameters: [
        [$class: 'StringParameterValue', name: 'INVENTORY', value: INVENTORY],
        [$class: 'StringParameterValue', name: 'LIMIT', value: LIMIT],
        [$class: 'StringParameterValue', name: 'PLAYBOOK', value: PLAYBOOK],
        [$class: 'StringParameterValue', name: 'EXTRA_PARAMS', value: EXTRA_PARAMS]]
}

def checkLog() {

    def logFile = input(
        id: 'userInput', message: 'Enter log filename :?',
        parameters: [
            string(defaultValue: 'None',
                description: 'Log file to check.',
                name: 'logFile'), ]
    )
    println("Check log file ${logFile}")
    build job: 'run_chklog', propagate: true, wait: true, parameters: [
        [$class: 'StringParameterValue', name: 'LOGFILE', value: logFile]]
}